# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  director: 'logs'
  link-name: 'latest_log'
  show-line: true
  # LowercaseLevelEncoder:小写, LowercaseColorLevelEncoder:小写带颜色,CapitalLevelEncoder: 大写, CapitalColorLevelEncoder: 大写带颜色,
  encode-level: 'CapitalLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

# mysql configuration
mysql:
  path: '127.0.0.1:3306'
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  db-name: 'pigs'
  username: 'root'
  password: '123456'
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: true
  log-zap: ""

# casbin configuration
casbin:
  model-path: './resource/rbac_model.conf'

# system configuration
system:
  env: 'public'  # Change to "develop" to skip authentication for development mode,  public auth
  addr: 8999
  db-type: 'mysql'