name: Go

on:
  push:
    branches: "*"
  pull_request:

jobs:

  build:
    name: ubuntu - Go v1.14
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.7'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@master

      - name: Save build binaries
        uses: gpre;easer/goreleaser-action@v1
        with:
          version: latest
          args: release --snapshot --rm-dist
